import { ClientFollowUp } from './types';

export const INITIAL_CLIENTS: ClientFollowUp[] = [
  {
    id: 'cli-001',
    fullName: 'محمد العلوي',
    cin: 'AB123456',
    phone: '0661234567',
    email: 'm.alaoui@notary-mail.ma',
    address: 'شارع الحسن الثاني، عمارة 14، الشقة 6، فاس',
    avatarColor: 'bg-blue-800',
    clientSinceYear: 2019,
    currentDeed: {
      deedType: 'شراء عقار',
      ledgerNumber: '24',
      deedNumber: '136',
      receiptDate: '2026-03-01',
      workflowStatus: 'مسودة_للمعاينة',
      statusNotes: 'المسودة منجزة وجاهزة للمعاينة وإبداء الملاحظات',
    },
    financials: {
      status: 'due',
      totalAmount: 11300,
      totalPaid: 8800,
      totalRemaining: 2500,
      items: [
        {
          key: 'registration_and_stamp',
          title: 'واجب التسجيل والتمبر',
          total: 7000,
          paid: 7000,
          remaining: 0,
        },
        {
          key: 'notary_fee',
          title: 'أجرة العدل',
          total: 3500,
          paid: 1000,
          remaining: 2500,
        },
        {
          key: 'tax_declaration',
          title: 'التصريح بالضريبة (الأرباح العقارية)',
          total: 500,
          paid: 500,
          remaining: 0,
        },
        {
          key: 'admin_certificates',
          title: 'الشواهد الإدارية وإيداع الملف',
          total: 300,
          paid: 300,
          remaining: 0,
        },
      ],
      payments: [
        {
          id: 'pay-1',
          date: '2026-03-02',
          amount: 7000,
          method: 'تحويل بنكي',
          notes: 'تسديد واجب التسجيل والتمبر لإدارة الضرائب',
          remainingAfter: 4300,
        },
        {
          id: 'pay-2',
          date: '2026-03-08',
          amount: 1800,
          method: 'نقد',
          notes: 'تسبيق أجرة العدل والمصاريف الإدارية',
          remainingAfter: 2500,
        },
      ],
    },
    alerts: [
      {
        id: 'alt-1',
        type: 'financial',
        title: 'متبقي مالي بالذمة',
        description: 'متبقي بذمته 2,500 درهم عن أجرة العدل منذ 15 يوماً',
        date: '2026-03-15',
      },
      {
        id: 'alt-2',
        type: 'followup',
        title: 'معاينة المسودة',
        description: 'المسودة أرسلت منذ 3 أيام ولم يؤكد المعاينة بعد',
        date: '2026-03-16',
      },
    ],
    communications: [
      {
        id: 'c-5',
        timestamp: '15/03/2026 – 16:00',
        date: '2026-03-15',
        time: '16:00',
        channel: 'system',
        iconType: 'bell',
        title: 'تذكير مالي تلقائي',
        description: 'تذكير بمقتضى النظام: متبقي بذمتكم 2,500 درهم برسم أجرة التوثيق.',
        author: 'النظام الآلي للمكتب',
      },
      {
        id: 'c-4',
        timestamp: '14/03/2026 – 11:00',
        date: '2026-03-14',
        time: '11:00',
        channel: 'system',
        iconType: 'money',
        title: 'أداء دفعة مالية',
        description: 'تم أداء دفعة قدرها 1,000 درهم نقداً وخصمها من أجرة العدل.',
        author: 'العدل الممارس',
      },
      {
        id: 'c-3',
        timestamp: '13/03/2026 – 09:00',
        date: '2026-03-13',
        time: '09:00',
        channel: 'whatsapp',
        iconType: 'update',
        title: 'تحديث المسودة وإعادة الإرسال',
        description: 'تم تحيين بيانات العقار وإعادة إرسال المسودة للمراجعة عبر WhatsApp.',
        author: 'العدل الممارس',
      },
      {
        id: 'c-2',
        timestamp: '12/03/2026 – 14:15',
        date: '2026-03-12',
        time: '14:15',
        channel: 'client_feedback',
        iconType: 'note',
        title: 'ملاحظة من طالب الإشهاد',
        description: '«تمت المعاينة الأولية، أرجو تصحيح تاريخ الازدياد الخاص بي في ديباجة العقد».',
        author: 'طالب الإشهاد',
      },
      {
        id: 'c-1',
        timestamp: '12/03/2026 – 10:30',
        date: '2026-03-12',
        time: '10:30',
        channel: 'whatsapp',
        iconType: 'send',
        title: 'إرسال مسودة الرسم عبر WhatsApp',
        description: 'تم إرسال رابط مسودة عقد الشراء بصيغة PDF المشفرة للاطلاع.',
        author: 'مكتب التوثيق',
      },
    ],
    deedHistory: [
      {
        id: 'h-1',
        year: 2024,
        deedType: 'شراء',
        reference: 'سجل 24 / عدد 136',
        fees: 3500,
        status: 'remaining',
        remainingAmount: 2500,
        notes: 'الرسم الجاري قيد المتابعة والأداء الجزئي',
      },
      {
        id: 'h-2',
        year: 2022,
        deedType: 'وكالة مفوضة',
        reference: 'سجل 22 / عدد 89',
        fees: 800,
        status: 'settled',
        notes: 'معاملة مسواة بالكامل وخالصة الذمة في حينها',
      },
      {
        id: 'h-3',
        year: 2019,
        deedType: 'هبة عقار',
        reference: 'سجل 19 / عدد 45',
        fees: 2000,
        status: 'settled',
        notes: 'مسواة بالكامل ومضمنة بسجل الرسوم العقارية',
      },
    ],
  },
  {
    id: 'cli-002',
    fullName: 'أحمد بنجلون',
    cin: 'CD789123',
    phone: '0662345678',
    email: 'ahmed.benjelloun@domain.ma',
    address: 'حي الرياض، زنقة النخيل، فيلا 22، الرباط',
    avatarColor: 'bg-emerald-800',
    clientSinceYear: 2021,
    currentDeed: {
      deedType: 'رسم هبة',
      ledgerNumber: '24',
      deedNumber: '140',
      receiptDate: '2026-02-20',
      workflowStatus: 'تم_إنجاز_الرسم',
      statusNotes: 'تم إنجاز الرسم وتضمينه بسجلات المحكمة الابتدائية',
    },
    financials: {
      status: 'settled',
      totalAmount: 4800,
      totalPaid: 4800,
      totalRemaining: 0,
      items: [
        {
          key: 'registration_and_stamp',
          title: 'واجب التسجيل والتمبر',
          total: 2500,
          paid: 2500,
          remaining: 0,
        },
        {
          key: 'notary_fee',
          title: 'أجرة العدل',
          total: 2000,
          paid: 2000,
          remaining: 0,
        },
        {
          key: 'admin_certificates',
          title: 'مصاريف الملف الإداري',
          total: 300,
          paid: 300,
          remaining: 0,
        },
      ],
      payments: [
        {
          id: 'pay-b1',
          date: '2026-02-21',
          amount: 4800,
          method: 'شيك',
          notes: 'أداء شامل بشيك بنكي مسحوب على التجاري وفا بنك',
          remainingAfter: 0,
        },
      ],
    },
    alerts: [],
    communications: [
      {
        id: 'c-b1',
        timestamp: '25/02/2026 – 12:00',
        date: '2026-02-25',
        time: '12:00',
        channel: 'whatsapp',
        iconType: 'check',
        title: 'تسليم النسخة الرسمية',
        description: 'تم تسليم النسخة التنفيذية المضمنة لطالب الإشهاد وخلو الذمة.',
        author: 'كتابة العدل',
      },
    ],
    deedHistory: [
      {
        id: 'hb-1',
        year: 2026,
        deedType: 'هبة',
        reference: 'سجل 24 / عدد 140',
        fees: 2000,
        status: 'settled',
        notes: 'مسواة بالكامل',
      },
      {
        id: 'hb-2',
        year: 2021,
        deedType: 'مخالطة وشركة',
        reference: 'سجل 21 / عدد 62',
        fees: 1500,
        status: 'settled',
        notes: 'مسواة بالكامل',
      },
    ],
  },
  {
    id: 'cli-003',
    fullName: 'فاطمة الزهراء الإدريسي',
    cin: 'EE456123',
    phone: '0663456789',
    email: 'f.idrissi@post.ma',
    address: 'المعارف، زنقة البساتين، إقامة الهدى، الدار البيضاء',
    avatarColor: 'bg-amber-700',
    clientSinceYear: 2023,
    currentDeed: {
      deedType: 'رسم صدقة عقارية',
      ledgerNumber: '24',
      deedNumber: '142',
      receiptDate: '2026-03-05',
      workflowStatus: 'توجد_ملاحظات',
      statusNotes: 'بانتظار الإدلاء بأصل التملك المكتوب',
    },
    financials: {
      status: 'partial',
      totalAmount: 3200,
      totalPaid: 2000,
      totalRemaining: 1200,
      items: [
        {
          key: 'registration_and_stamp',
          title: 'واجب التسجيل والتمبر',
          total: 1500,
          paid: 1500,
          remaining: 0,
        },
        {
          key: 'notary_fee',
          title: 'أجرة العدل',
          total: 1400,
          paid: 200,
          remaining: 1200,
        },
        {
          key: 'admin_certificates',
          title: 'شهادة إدارية ورسوم بلدية',
          total: 300,
          paid: 300,
          remaining: 0,
        },
      ],
      payments: [
        {
          id: 'pay-f1',
          date: '2026-03-06',
          amount: 2000,
          method: 'نقد',
          notes: 'تسبيق واجب التسجيل ومصروف الملف',
          remainingAfter: 1200,
        },
      ],
    },
    alerts: [
      {
        id: 'alt-f1',
        type: 'correction',
        title: 'ملاحظة على المسودة',
        description: 'توجد ملاحظات من طالبة الإشهاد بخصوص حدود العقار المتصدق به',
        date: '2026-03-14',
      },
    ],
    communications: [
      {
        id: 'c-f1',
        timestamp: '14/03/2026 – 15:30',
        date: '2026-03-14',
        time: '15:30',
        channel: 'whatsapp',
        iconType: 'note',
        title: 'إفادة من المعنية بالأمر',
        description: 'أرسلت نسخة من التصميم الطبوغرافي لتعديل الحد الشرقي.',
        author: 'طالبة الإشهاد',
      },
    ],
    deedHistory: [
      {
        id: 'hf-1',
        year: 2026,
        deedType: 'صدقة',
        reference: 'سجل 24 / عدد 142',
        fees: 1400,
        status: 'remaining',
        remainingAmount: 1200,
      },
      {
        id: 'hf-2',
        year: 2023,
        deedType: 'استمرار ملك',
        reference: 'سجل 23 / عدد 112',
        fees: 2500,
        status: 'settled',
      },
    ],
  },
  {
    id: 'cli-004',
    fullName: 'عبد الرحيم التازي',
    cin: 'K345678',
    phone: '0664567890',
    email: 'tazi.abderrahim@avocat.ma',
    address: 'شارع الزرقطوني، درب عمر، الدار البيضاء',
    avatarColor: 'bg-cyan-800',
    clientSinceYear: 2020,
    currentDeed: {
      deedType: 'إحصاء تركة ومتروك',
      ledgerNumber: '24',
      deedNumber: '145',
      receiptDate: '2026-03-10',
      workflowStatus: 'أرسلت_المسودة',
      statusNotes: 'بانتظار جواب الورثة وشهادة الإبراء الضريبي للتركة',
    },
    financials: {
      status: 'followup',
      totalAmount: 6000,
      totalPaid: 6000,
      totalRemaining: 0,
      items: [
        {
          key: 'registration_and_stamp',
          title: 'واجب التسجيل والتمبر',
          total: 2000,
          paid: 2000,
          remaining: 0,
        },
        {
          key: 'notary_fee',
          title: 'أجرة العدل',
          total: 3500,
          paid: 3500,
          remaining: 0,
        },
        {
          key: 'admin_certificates',
          title: 'شهادة الوفاة وإحصاء الرسوم',
          total: 500,
          paid: 500,
          remaining: 0,
        },
      ],
      payments: [
        {
          id: 'pay-t1',
          date: '2026-03-10',
          amount: 6000,
          method: 'تحويل بنكي',
          notes: 'تسوية مسبقة شاملة لكافة الأتعاب والمصاريف',
          remainingAfter: 0,
        },
      ],
    },
    alerts: [
      {
        id: 'alt-t1',
        type: 'procedure',
        title: 'متابعة إدارية خارجية',
        description: 'شهادة عدم فرض الضريبة على التركة قيد الإنجاز بمديرية الضرائب',
        date: '2026-03-18',
      },
    ],
    communications: [
      {
        id: 'c-t1',
        timestamp: '16/03/2026 – 10:15',
        date: '2026-03-16',
        time: '10:15',
        channel: 'email',
        iconType: 'send',
        title: 'إرسال مشروع الإحصاء لجميع الورثة',
        description: 'تم إرسال جدول التركة التفصيلي لمصادقة الورثة قبل التضمين.',
        author: 'مكتب التوثيق',
      },
    ],
    deedHistory: [
      {
        id: 'ht-1',
        year: 2026,
        deedType: 'إحصاء تركة',
        reference: 'سجل 24 / عدد 145',
        fees: 3500,
        status: 'settled',
      },
      {
        id: 'ht-2',
        year: 2020,
        deedType: 'قسمة بتية رضائية',
        reference: 'سجل 20 / عدد 78',
        fees: 4000,
        status: 'settled',
      },
    ],
  },
  {
    id: 'cli-005',
    fullName: 'مريم العمراني',
    cin: 'BH998877',
    phone: '0665678901',
    email: 'mariam.amrani@gmail.com',
    address: 'شارع محمد السادس، إقامة الياسمين، مراكش',
    avatarColor: 'bg-rose-800',
    clientSinceYear: 2022,
    currentDeed: {
      deedType: 'اعتصار هبة',
      ledgerNumber: '24',
      deedNumber: '149',
      receiptDate: '2026-03-14',
      workflowStatus: 'مسودة_للمعاينة',
      statusNotes: 'إعداد اعتصار اتفاقي بين الواهب والموهوب له',
    },
    financials: {
      status: 'due',
      totalAmount: 4200,
      totalPaid: 1500,
      totalRemaining: 2700,
      items: [
        {
          key: 'registration_and_stamp',
          title: 'واجب التسجيل والتمبر',
          total: 2000,
          paid: 1500,
          remaining: 500,
        },
        {
          key: 'notary_fee',
          title: 'أجرة العدل',
          total: 2000,
          paid: 0,
          remaining: 2000,
        },
        {
          key: 'admin_certificates',
          title: 'المصاريف التبعية',
          total: 200,
          paid: 0,
          remaining: 200,
        },
      ],
      payments: [
        {
          id: 'pay-m1',
          date: '2026-03-14',
          amount: 1500,
          method: 'نقد',
          notes: 'تسبيق واجب التسجيل',
          remainingAfter: 2700,
        },
      ],
    },
    alerts: [
      {
        id: 'alt-m1',
        type: 'financial',
        title: 'مستحق غير مؤدى',
        description: 'متبقي 2,700 درهم يتضمن جزءاً من واجب التسجيل وأجرة العدل',
        date: '2026-03-17',
      },
    ],
    communications: [
      {
        id: 'c-m1',
        timestamp: '14/03/2026 – 16:20',
        date: '2026-03-14',
        time: '16:20',
        channel: 'whatsapp',
        iconType: 'send',
        title: 'تأكيد الحضور للتوقيع',
        description: 'إرسال إشعار للواهب والموهوب له للحضور المشترك للمكتب.',
        author: 'مكتب التوثيق',
      },
    ],
    deedHistory: [
      {
        id: 'hm-1',
        year: 2026,
        deedType: 'اعتصار هبة',
        reference: 'سجل 24 / عدد 149',
        fees: 2000,
        status: 'remaining',
        remainingAmount: 2700,
      },
      {
        id: 'hm-2',
        year: 2022,
        deedType: 'رسم هبة',
        reference: 'سجل 22 / عدد 101',
        fees: 1800,
        status: 'settled',
      },
    ],
  },
  {
    id: 'cli-006',
    fullName: 'رشيد بوشعيب',
    cin: 'G654321',
    phone: '0666789012',
    email: 'r.bouchaib@menara.ma',
    address: 'شارع طارق بن زياد، قنيطرة',
    avatarColor: 'bg-indigo-900',
    clientSinceYear: 2024,
    currentDeed: {
      deedType: 'موجب إثبات غيبة',
      ledgerNumber: '24',
      deedNumber: '152',
      receiptDate: '2026-03-18',
      workflowStatus: 'تم_تحديث_المسودة',
      statusNotes: 'تحيين أسماء شهود اللفيف وتدوين عناوينهم',
    },
    financials: {
      status: 'partial',
      totalAmount: 2200,
      totalPaid: 1500,
      totalRemaining: 700,
      items: [
        {
          key: 'registration_and_stamp',
          title: 'واجب التسجيل والتمبر',
          total: 500,
          paid: 500,
          remaining: 0,
        },
        {
          key: 'notary_fee',
          title: 'أجرة العدل',
          total: 1500,
          paid: 1000,
          remaining: 500,
        },
        {
          key: 'admin_certificates',
          title: 'المصاريف الإدارية',
          total: 200,
          paid: 0,
          remaining: 200,
        },
      ],
      payments: [
        {
          id: 'pay-r1',
          date: '2026-03-18',
          amount: 1500,
          method: 'نقد',
          notes: 'تسديد التسجيل وتسبيق الأجرة',
          remainingAfter: 700,
        },
      ],
    },
    alerts: [
      {
        id: 'alt-r1',
        type: 'followup',
        title: 'حضور الشهود',
        description: 'موعد تلقي إشهاد اللفيف محدد ليوم الغد صباحاً',
        date: '2026-03-20',
      },
    ],
    communications: [
      {
        id: 'c-r1',
        timestamp: '19/03/2026 – 11:30',
        date: '2026-03-19',
        time: '11:30',
        channel: 'sms',
        iconType: 'bell',
        title: 'رسالة نصية بتأكيد موعد اللفيف',
        description: 'تم إرسال رسالة قصيرة بتذكير موعد حضور شهود اللفيف الإثني عشر.',
        author: 'مكتب التوثيق',
      },
    ],
    deedHistory: [
      {
        id: 'hr-1',
        year: 2026,
        deedType: 'موجب غيبة',
        reference: 'سجل 24 / عدد 152',
        fees: 1500,
        status: 'remaining',
        remainingAmount: 700,
      },
    ],
  },
];
