import { z } from 'zod';
declare const marriageDocumentSubjectSchema: z.ZodEnum<["husband", "wife", "other"]>;
export declare const notarySchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    full_name: z.ZodString;
    cin: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    tax_id: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    appointment_number: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    start_date: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    office_location: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    region: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    phone: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    email: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    photo_url: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    full_name?: string;
    cin?: string;
    tax_id?: string;
    appointment_number?: string;
    start_date?: string;
    office_location?: string;
    region?: string;
    phone?: string;
    email?: string;
    photo_url?: string;
    description?: string;
}, {
    id?: string;
    full_name?: string;
    cin?: string;
    tax_id?: string;
    appointment_number?: string;
    start_date?: string;
    office_location?: string;
    region?: string;
    phone?: string;
    email?: string;
    photo_url?: string;
    description?: string;
}>;
export declare const marriageDocumentSchema: z.ZodObject<{
    id: z.ZodString;
    marriage_record_id: z.ZodString;
    file_name: z.ZodString;
    file_url: z.ZodString;
    file_type: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    file_size: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    subject: z.ZodNullable<z.ZodOptional<z.ZodEnum<["husband", "wife", "other"]>>>;
    ocr_raw_text: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    ocr_detected_fields: z.ZodNullable<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>>;
    created_at: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    updated_at: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    marriage_record_id?: string;
    file_name?: string;
    file_url?: string;
    file_type?: string;
    file_size?: number;
    subject?: "husband" | "wife" | "other";
    ocr_raw_text?: string;
    ocr_detected_fields?: Record<string, string>;
    created_at?: string;
    updated_at?: string;
}, {
    id?: string;
    marriage_record_id?: string;
    file_name?: string;
    file_url?: string;
    file_type?: string;
    file_size?: number;
    subject?: "husband" | "wife" | "other";
    ocr_raw_text?: string;
    ocr_detected_fields?: Record<string, string>;
    created_at?: string;
    updated_at?: string;
}>;
export declare const marriageRecordSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    record_type: z.ZodEnum<["adult", "minor", "mixed", "disabled"]>;
    fee_type: z.ZodString;
    inclusion_date: z.ZodString;
    inclusion_hijri: z.ZodString;
    husband_name: z.ZodString;
    husband_cin: z.ZodString;
    husband_birth_date: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    husband_nationality: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    husband_is_muslim: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    husband_marital_status: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    husband_residence: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    husband_occupation: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    wife_name: z.ZodString;
    wife_cin: z.ZodString;
    wife_birth_date: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    wife_nationality: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    wife_is_muslim: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    wife_marital_status: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    wife_residence: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    wife_occupation: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    is_minor_husband: z.ZodDefault<z.ZodBoolean>;
    is_minor_wife: z.ZodDefault<z.ZodBoolean>;
    minor_husband_permit_file_no: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    minor_wife_permit_file_no: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    mixed_marriage_husband_passport_no: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    mixed_marriage_wife_passport_no: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    husband_disability_type: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    wife_disability_type: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    marriage_authorization_no: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    dowry_amount: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    investment_of_assets_agreed: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    contracted_by: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    registry_book_type: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    registry_number: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    registry_count: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    registry_letter: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    registry_page: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    source_document_ref: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    document_url: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    document_name: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    husband_previous_divorce_ref: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    documents: z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        marriage_record_id: z.ZodString;
        file_name: z.ZodString;
        file_url: z.ZodString;
        file_type: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        file_size: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
        subject: z.ZodNullable<z.ZodOptional<z.ZodEnum<["husband", "wife", "other"]>>>;
        ocr_raw_text: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        ocr_detected_fields: z.ZodNullable<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>>;
        created_at: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        updated_at: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    }, "strip", z.ZodTypeAny, {
        id?: string;
        marriage_record_id?: string;
        file_name?: string;
        file_url?: string;
        file_type?: string;
        file_size?: number;
        subject?: "husband" | "wife" | "other";
        ocr_raw_text?: string;
        ocr_detected_fields?: Record<string, string>;
        created_at?: string;
        updated_at?: string;
    }, {
        id?: string;
        marriage_record_id?: string;
        file_name?: string;
        file_url?: string;
        file_type?: string;
        file_size?: number;
        subject?: "husband" | "wife" | "other";
        ocr_raw_text?: string;
        ocr_detected_fields?: Record<string, string>;
        created_at?: string;
        updated_at?: string;
    }>, "many">>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    record_type?: "adult" | "minor" | "mixed" | "disabled";
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    husband_name?: string;
    husband_cin?: string;
    husband_birth_date?: string;
    husband_nationality?: string;
    husband_is_muslim?: boolean;
    husband_marital_status?: string;
    husband_residence?: string;
    husband_occupation?: string;
    wife_name?: string;
    wife_cin?: string;
    wife_birth_date?: string;
    wife_nationality?: string;
    wife_is_muslim?: boolean;
    wife_marital_status?: string;
    wife_residence?: string;
    wife_occupation?: string;
    is_minor_husband?: boolean;
    is_minor_wife?: boolean;
    minor_husband_permit_file_no?: string;
    minor_wife_permit_file_no?: string;
    mixed_marriage_husband_passport_no?: string;
    mixed_marriage_wife_passport_no?: string;
    husband_disability_type?: string;
    wife_disability_type?: string;
    marriage_authorization_no?: string;
    dowry_amount?: number;
    investment_of_assets_agreed?: boolean;
    contracted_by?: string;
    registry_book_type?: string;
    registry_number?: number;
    registry_count?: number;
    registry_letter?: string;
    registry_page?: number;
    source_document_ref?: string;
    document_url?: string;
    document_name?: string;
    notes?: string;
    husband_previous_divorce_ref?: string;
    documents?: {
        id?: string;
        marriage_record_id?: string;
        file_name?: string;
        file_url?: string;
        file_type?: string;
        file_size?: number;
        subject?: "husband" | "wife" | "other";
        ocr_raw_text?: string;
        ocr_detected_fields?: Record<string, string>;
        created_at?: string;
        updated_at?: string;
    }[];
}, {
    id?: string;
    record_type?: "adult" | "minor" | "mixed" | "disabled";
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    husband_name?: string;
    husband_cin?: string;
    husband_birth_date?: string;
    husband_nationality?: string;
    husband_is_muslim?: boolean;
    husband_marital_status?: string;
    husband_residence?: string;
    husband_occupation?: string;
    wife_name?: string;
    wife_cin?: string;
    wife_birth_date?: string;
    wife_nationality?: string;
    wife_is_muslim?: boolean;
    wife_marital_status?: string;
    wife_residence?: string;
    wife_occupation?: string;
    is_minor_husband?: boolean;
    is_minor_wife?: boolean;
    minor_husband_permit_file_no?: string;
    minor_wife_permit_file_no?: string;
    mixed_marriage_husband_passport_no?: string;
    mixed_marriage_wife_passport_no?: string;
    husband_disability_type?: string;
    wife_disability_type?: string;
    marriage_authorization_no?: string;
    dowry_amount?: number;
    investment_of_assets_agreed?: boolean;
    contracted_by?: string;
    registry_book_type?: string;
    registry_number?: number;
    registry_count?: number;
    registry_letter?: string;
    registry_page?: number;
    source_document_ref?: string;
    document_url?: string;
    document_name?: string;
    notes?: string;
    husband_previous_divorce_ref?: string;
    documents?: {
        id?: string;
        marriage_record_id?: string;
        file_name?: string;
        file_url?: string;
        file_type?: string;
        file_size?: number;
        subject?: "husband" | "wife" | "other";
        ocr_raw_text?: string;
        ocr_detected_fields?: Record<string, string>;
        created_at?: string;
        updated_at?: string;
    }[];
}>;
export declare const divorceRecordSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    divorce_type: z.ZodEnum<["shiqaq", "agreement", "khul", "mamluk", "complete_three", "bain"]>;
    fee_type: z.ZodString;
    inclusion_date: z.ZodString;
    inclusion_hijri: z.ZodString;
    husband_name: z.ZodString;
    husband_cin: z.ZodString;
    wife_name: z.ZodString;
    wife_cin: z.ZodString;
    judgment_number: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    divorce_witnessing_date: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    marriage_registry_number: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    marriage_registry_count: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    marriage_registry_page: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    divorce_registry_book_type: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    divorce_registry_number: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    divorce_registry_count: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    divorce_registry_letter: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    divorce_registry_page: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    husband_birth_date: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    wife_birth_date: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    occupations: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    nationality: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    number_of_children: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    cohabiting: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    document_url: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    document_name: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    husband_name?: string;
    husband_cin?: string;
    husband_birth_date?: string;
    wife_name?: string;
    wife_cin?: string;
    wife_birth_date?: string;
    document_url?: string;
    document_name?: string;
    divorce_type?: "shiqaq" | "agreement" | "khul" | "mamluk" | "complete_three" | "bain";
    judgment_number?: string;
    divorce_witnessing_date?: string;
    marriage_registry_number?: string;
    marriage_registry_count?: number;
    marriage_registry_page?: number;
    divorce_registry_book_type?: string;
    divorce_registry_number?: number;
    divorce_registry_count?: number;
    divorce_registry_letter?: string;
    divorce_registry_page?: number;
    occupations?: string;
    nationality?: string;
    number_of_children?: number;
    cohabiting?: boolean;
}, {
    id?: string;
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    husband_name?: string;
    husband_cin?: string;
    husband_birth_date?: string;
    wife_name?: string;
    wife_cin?: string;
    wife_birth_date?: string;
    document_url?: string;
    document_name?: string;
    divorce_type?: "shiqaq" | "agreement" | "khul" | "mamluk" | "complete_three" | "bain";
    judgment_number?: string;
    divorce_witnessing_date?: string;
    marriage_registry_number?: string;
    marriage_registry_count?: number;
    marriage_registry_page?: number;
    divorce_registry_book_type?: string;
    divorce_registry_number?: number;
    divorce_registry_count?: number;
    divorce_registry_letter?: string;
    divorce_registry_page?: number;
    occupations?: string;
    nationality?: string;
    number_of_children?: number;
    cohabiting?: boolean;
}>;
export declare const propertyFeeSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    fee_type: z.ZodString;
    inclusion_date: z.ZodString;
    inclusion_hijri: z.ZodString;
    parties_names: z.ZodString;
    parties_cin: z.ZodString;
    transferor_name: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    transferor_parents_names: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    transferor_home_address: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    sellers_list: z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        cin: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        parents_names: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        home_address: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        fraction: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    }, "strip", z.ZodTypeAny, {
        cin?: string;
        name?: string;
        parents_names?: string;
        home_address?: string;
        fraction?: number;
    }, {
        cin?: string;
        name?: string;
        parents_names?: string;
        home_address?: string;
        fraction?: number;
    }>, "many">>>;
    buyers_list: z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        cin: z.ZodString;
        parents_names: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        home_address: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        fraction: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    }, "strip", z.ZodTypeAny, {
        cin?: string;
        name?: string;
        parents_names?: string;
        home_address?: string;
        fraction?: number;
    }, {
        cin?: string;
        name?: string;
        parents_names?: string;
        home_address?: string;
        fraction?: number;
    }>, "many">>>;
    registration_and_stamp_ref: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    property_coordinates: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    property_length_m: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    property_width_m: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    property_area_m2: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    geo_latitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    geo_longitude: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    purchase_method: z.ZodNullable<z.ZodOptional<z.ZodEnum<["بيع", "شراء", "اعترافا", "هبة", "وصية"]>>>;
    registry_book_type: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    registry_number: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    registry_count: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    registry_letter: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    registry_page: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    source_document_ref: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    document_url: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    document_name: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    registry_book_type?: string;
    registry_number?: number;
    registry_count?: number;
    registry_letter?: string;
    registry_page?: number;
    source_document_ref?: string;
    document_url?: string;
    document_name?: string;
    parties_names?: string;
    parties_cin?: string;
    transferor_name?: string;
    transferor_parents_names?: string;
    transferor_home_address?: string;
    sellers_list?: {
        cin?: string;
        name?: string;
        parents_names?: string;
        home_address?: string;
        fraction?: number;
    }[];
    buyers_list?: {
        cin?: string;
        name?: string;
        parents_names?: string;
        home_address?: string;
        fraction?: number;
    }[];
    registration_and_stamp_ref?: string;
    property_coordinates?: string;
    property_length_m?: number;
    property_width_m?: number;
    property_area_m2?: number;
    geo_latitude?: number;
    geo_longitude?: number;
    purchase_method?: "بيع" | "شراء" | "اعترافا" | "هبة" | "وصية";
}, {
    id?: string;
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    registry_book_type?: string;
    registry_number?: number;
    registry_count?: number;
    registry_letter?: string;
    registry_page?: number;
    source_document_ref?: string;
    document_url?: string;
    document_name?: string;
    parties_names?: string;
    parties_cin?: string;
    transferor_name?: string;
    transferor_parents_names?: string;
    transferor_home_address?: string;
    sellers_list?: {
        cin?: string;
        name?: string;
        parents_names?: string;
        home_address?: string;
        fraction?: number;
    }[];
    buyers_list?: {
        cin?: string;
        name?: string;
        parents_names?: string;
        home_address?: string;
        fraction?: number;
    }[];
    registration_and_stamp_ref?: string;
    property_coordinates?: string;
    property_length_m?: number;
    property_width_m?: number;
    property_area_m2?: number;
    geo_latitude?: number;
    geo_longitude?: number;
    purchase_method?: "بيع" | "شراء" | "اعترافا" | "هبة" | "وصية";
}>;
export declare const inheritanceFeeSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    fee_type: z.ZodString;
    inclusion_date: z.ZodString;
    inclusion_hijri: z.ZodString;
    deceased_name: z.ZodString;
    heirs_names: z.ZodString;
    applicants_cin: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    document_references: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    registry_book_type: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    registry_number: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    registry_count: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    registry_letter: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    registry_page: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    document_url: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    document_name: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    registry_book_type?: string;
    registry_number?: number;
    registry_count?: number;
    registry_letter?: string;
    registry_page?: number;
    document_url?: string;
    document_name?: string;
    deceased_name?: string;
    heirs_names?: string;
    applicants_cin?: string;
    document_references?: string;
}, {
    id?: string;
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    registry_book_type?: string;
    registry_number?: number;
    registry_count?: number;
    registry_letter?: string;
    registry_page?: number;
    document_url?: string;
    document_name?: string;
    deceased_name?: string;
    heirs_names?: string;
    applicants_cin?: string;
    document_references?: string;
}>;
export declare const otherDocumentFeeSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    fee_type: z.ZodString;
    inclusion_date: z.ZodString;
    inclusion_hijri: z.ZodString;
    applicants_names: z.ZodString;
    applicants_cin: z.ZodString;
    document_refs: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    is_in_inheritance_registry: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    registry_number: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    registry_count: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    registry_page: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    document_url: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    document_name: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    registry_number?: number;
    registry_count?: number;
    registry_page?: number;
    document_url?: string;
    document_name?: string;
    applicants_cin?: string;
    applicants_names?: string;
    document_refs?: string;
    is_in_inheritance_registry?: boolean;
}, {
    id?: string;
    fee_type?: string;
    inclusion_date?: string;
    inclusion_hijri?: string;
    registry_number?: number;
    registry_count?: number;
    registry_page?: number;
    document_url?: string;
    document_name?: string;
    applicants_cin?: string;
    applicants_names?: string;
    document_refs?: string;
    is_in_inheritance_registry?: boolean;
}>;
export declare const copyRequestSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    record_type: z.ZodString;
    reference_ids: z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    requester_name: z.ZodString;
    requester_cin: z.ZodString;
    request_date: z.ZodString;
    status: z.ZodDefault<z.ZodEnum<["pending", "processed"]>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    primary_court: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    record_year: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    record_details: z.ZodNullable<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    assigned_notary_ids: z.ZodNullable<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    routing_mode: z.ZodNullable<z.ZodOptional<z.ZodEnum<["direct", "historical_selection"]>>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    status?: "pending" | "processed";
    record_type?: string;
    notes?: string;
    reference_ids?: string[];
    requester_name?: string;
    requester_cin?: string;
    request_date?: string;
    primary_court?: string;
    record_year?: number;
    record_details?: Record<string, unknown>;
    assigned_notary_ids?: string[];
    routing_mode?: "direct" | "historical_selection";
}, {
    id?: string;
    status?: "pending" | "processed";
    record_type?: string;
    notes?: string;
    reference_ids?: string[];
    requester_name?: string;
    requester_cin?: string;
    request_date?: string;
    primary_court?: string;
    record_year?: number;
    record_details?: Record<string, unknown>;
    assigned_notary_ids?: string[];
    routing_mode?: "direct" | "historical_selection";
}>;
export declare const contractSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    contract_type: z.ZodString;
    title: z.ZodString;
    body: z.ZodString;
    ai_notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    legal_review: z.ZodNullable<z.ZodOptional<z.ZodAny>>;
    storage_document_id: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    contract_type?: string;
    title?: string;
    body?: string;
    ai_notes?: string;
    legal_review?: any;
    storage_document_id?: string;
}, {
    id?: string;
    contract_type?: string;
    title?: string;
    body?: string;
    ai_notes?: string;
    legal_review?: any;
    storage_document_id?: string;
}>;
export declare const contractTemplateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    template_type: z.ZodString;
    content: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id?: string;
    name?: string;
    template_type?: string;
    content?: string;
}, {
    id?: string;
    name?: string;
    template_type?: string;
    content?: string;
}>;
export declare const registrationStampSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    record_type: z.ZodString;
    record_id: z.ZodString;
    registration_number: z.ZodString;
    tax_value: z.ZodNumber;
    paid_date: z.ZodString;
    office: z.ZodString;
    receipt_ref: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    id?: string;
    record_type?: string;
    record_id?: string;
    registration_number?: string;
    tax_value?: number;
    paid_date?: string;
    office?: string;
    receipt_ref?: string;
}, {
    id?: string;
    record_type?: string;
    record_id?: string;
    registration_number?: string;
    tax_value?: number;
    paid_date?: string;
    office?: string;
    receipt_ref?: string;
}>;
export type Notary = z.infer<typeof notarySchema>;
export type MarriageRecord = z.infer<typeof marriageRecordSchema>;
export type MarriageDocument = z.infer<typeof marriageDocumentSchema>;
export type MarriageDocumentSubject = z.infer<typeof marriageDocumentSubjectSchema>;
export type DivorceRecord = z.infer<typeof divorceRecordSchema>;
export type PropertyFee = z.infer<typeof propertyFeeSchema>;
export type InheritanceFee = z.infer<typeof inheritanceFeeSchema>;
export type OtherDocumentFee = z.infer<typeof otherDocumentFeeSchema>;
export type CopyRequest = z.infer<typeof copyRequestSchema>;
export type Contract = z.infer<typeof contractSchema>;
export type ContractTemplate = z.infer<typeof contractTemplateSchema>;
export type RegistrationStamp = z.infer<typeof registrationStampSchema>;
export {};
